server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: kraven-ui-example
  main:
    allow-bean-definition-overriding: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kraven-example-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Application Configuration
app:
  api:
    base-url: http://localhost:8081

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

# Kraven UI Configuration
kraven:
  ui:
    path: /kraven
    development-mode: true
    feign-client:
      enabled: true
      base-packages: io.github.rohitect.kraven.example.client
    logging:
      level: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  packages-to-scan: io.github.rohitect.kraven.example.controller
  paths-to-match: /**

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    io.github.rohitect.kraven: DEBUG
    org.springframework.web: INFO
    org.springframework.context.annotation: DEBUG
    org.springframework.beans.factory.support: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
