server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: kraven-ui-example

# Kraven UI Configuration
kraven:
  ui:
    path: /kraven
    development-mode: true
    feign-client:
      enabled: true
      base-packages: io.github.rohitect.kraven.example.client
    logging:
      level: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  packages-to-scan: io.github.rohitect.kraven.example.controller
  paths-to-match: /**

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    io.github.rohitect.kraven: DEBUG
    org.springframework.web: INFO
    org.springframework.context.annotation: DEBUG
    org.springframework.beans.factory.support: DEBUG
